PYTHON_TECHNOLOGIES = [
    "pytest",
    "helm",
    "jquery",
    "pytorch",
    "mlflow",
    "css",
    "kubeflow",
    "networking",
    "mongodb",
    "docker",
    "bootstrap",
    "coverage",
    "kafka",
    "travis ci",
    "node",
    "spacy",
    "salesforce crm",
    "drf",
    "postgresql",
    "algorithm",
    "js",
    "elasticsearch",
    "django",
    "pipenv",
    "terraform",
    "graphql",
    "django rest framework",
    "microservice",
    "websockets",
    "ml",
    "spark",
    "hadoop",
    "oop",
    "github",
    "tensorflow",
    "ci/cd",
    "machine learning",
    "sqlalchemy",
    "oauth2",
    "grafana",
    "selenium",
    "python",
    "unittest",
    "logstash",
    "nginx",
    "gitlab",
    "git",
    "dask",
    "rest",
    "flask",
    "aws",
    "jenkins",
    "api",
    "html",
    "linux",
    "kibana",
    "async",
    "redis",
    "ansible",
    "prometheus",
    "celery",
    "tfx",
    "react",
    "pydantic",
    "grpc",
    "numpy",
    "fastapi",
    "rabbitmq",
    "pandas",
    "javascript",
    "full stack",
    "beautifulsoup",
    "nose",
    "dash",
    "nosql",
    "aiohttp",
    "alembic",
    "sql",
    "streamlit",
    "kubernetes",
    "tornado",
    "ai",
    "asyncio",
    "apache",
    "gunicorn",
    "requests",
]

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/58.0.3029.110 Safari/537.3"
}
